### ISSUE TITLE
generate and check expires=<timestamp> query parameter

### ISSUE THREAD

**Issue by jessaustin** [jessaustin/koa-signed-url#1]
It seems that every real-world use of this module also needs an `expires` query parameter that is set to some timestamp in the future. So, that should be included in this module. We want another, optional, argument that can be passed to the `sign()` function, to indicate the desired expiry term in milliseconds. If that argument is present, the function will add the `expires` query parameter, with a timestamp that number of milliseconds in future, as well as the `sig` query parameter.

Then we want the middleware to look for the `expires` parameter (after verifying the signature of course) and enforce that that timestamp has not passed already.

Reliable clocks are important for this. Also this might be a good time to remove the regex from the code. Supposedly regexes are not to be trusted for parsing input when security is important.

**Comment by JoshZA** [comment]
:+1:
